CREATE DATABASE customManager;
USE customManager;
CREATE TABLE CUSTOMERS (
    CustomerID INT PRIMARY KEY,
    FullName VARCHAR(100),
    Email VARCHAR(100), 
    Age INT             
);
ALTER TABLE CUSTOMERS 
CHANGE Email Email VARCHAR(100) NOT NULL;

ALTER TABLE CUSTOMERS 
CHANGE Age Age INT CHECK(Age > 0);